version: 2
jobs:
  pr-check:
    working_directory: ~/webapp-backend
    docker:
      - image: circleci/node:13.11.0
      - image: circleci/mysql:8.0.20
        command: [--default-authentication-plugin=mysql_native_password]
        environment:
          MYSQL_ROOT_PASSWORD: test@123
          MYSQL_DATABASE: tdb_dev
          MYSQL_USER: user
          MYSQL_PASSWORD: passw0rd
    steps:
      - checkout
      - run:
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 10
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Install node_modules with npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
              - ./node_modules
      - run:
          name: Compiling and running unit tests
          command: npm test
  build:
    working_directory: ~/webapp-backend
    docker:
      - image: circleci/node:13.11.0
      - image: circleci/mysql:8.0.20
        command: [--default-authentication-plugin=mysql_native_password]
        environment:
          MYSQL_ROOT_PASSWORD: test@123
          MYSQL_DATABASE: tdb_dev
          MYSQL_USER: user
          MYSQL_PASSWORD: passw0rd
    steps:
      - checkout
      - run:
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 10
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Install node_modules with npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
              - ./node_modules
      - run:
          name: Compiling and running unit tests
          command: npm test

workflows:
  version: 2
  pr-check:
    jobs:
      - pr-check
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
